debug:
  true
logging:
  level:
    org.springframework: INFO
    com.fedtech: DEBUG
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.40.4.32:3306/db_pension_sy?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  db:
    readsize: 3
    read0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.40.4.32:3306/db_pension_sy?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    read1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.40.4.32:3306/db_pension_sy?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    read2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.40.4.32:3306/db_pension_sy?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    readCdr:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.0.221/asteriskcdrdb?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
       username: root
       password: root
    readIpccp:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.0.221/IPCCP?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
       username: root
       password: root
  redis:
      host: 10.40.4.32
      port: 6379
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  dubbo:
    application:
      name: call-provider
    registry:
      address: zookeeper://10.40.4.33:2181
    protocol:
      name: dubbo
      port: 20886
    scan: com.fedtech.pension.call.service
server:
  port: 8086